### ISSUE TITLE
'Could not find the secret with provided UUID'  response

### ISSUE THREAD

**Issue by e1nurh** [ShahriyarR/one-time-secret-share#24]

**Comment by e1nurh** [comment]
Sometimes when I click the 'Get secret value' button it shows me 'Could not find the secret with provided UUID'. But Sometimes works fine

**Comment by ShahriyarR** [comment]
Is it okay of you refresh the same link and get back the secret? or the secret also gets lost?

**Comment by e1nurh** [comment]
When I refresh the same link (once or more) I can see the secret when I press the 'Get secret value' button

**Comment by ShahriyarR** [comment]
Interesting. Let me check.

**Comment by ShahriyarR** [comment]
Added sleep and gunicorn with a single worker, it seems to be fixed.
